name: Volume Backup

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

concurrency:
  group: deploy

jobs:
  backup:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
      TF_VAR_location: "nbg1"
      TF_VAR_ssh_public_key: "${{ secrets.SSH_PUBLIC_KEY }}"
      TF_VAR_ssh_private_key: "${{ secrets.SSH_PRIVATE_KEY }}"

      AWS_ACCESS_KEY_ID: "${{ secrets.HCLOUD_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "${{ secrets.HCLOUD_SECRET_ACCESS_KEY }}"

      BACKUP_KEEP_COUNT: "5"
      BACKUP_BUCKET_LOCATION: "nbg1"
      BACKUP_BUCKET_NAME: "backup-volume-radio-fingerprinting"
      BACKUP_SSH_PRIVATE_KEY: "${{ secrets.SSH_PRIVATE_KEY }}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Backup worker1
        working-directory: terraform
        env:
          BACKUP_TERRAFORM_MODULE_NAME: "worker1"
        run: |
          terraform init
          export BACKUP_TERRAFORM_MODULE_PATH="module.${BACKUP_TERRAFORM_MODULE_NAME}"
          sh -x "./.terraform/modules/${BACKUP_TERRAFORM_MODULE_NAME}/pipeline-scripts/volume-backup.sh"
